[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*
board_build.partitions = default_8MB.csv
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1
build_flags =
    -DBOARD_HAS_PSRAM=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -std=gnu++17
    -Wno-return-type
